### ISSUE TITLE
NSInvalidArgumentException  on iOS,  React 0.40

### ISSUE THREAD

**Issue by airman00** [oblador/react-native-progress#40]
Hi,
I'm getting this issue thrown. Is this occurring for anyone else?

Setup:    
     "react": "15.4.2",
    "react-native": "^0.40.0",
    "react-native-progress": "^3.2.0",

Error: 
```
[__NSArrayI length]: unrecognized selector sent to instance 0x131a20af0
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayI length]: unrecognized selector sent to instance 0x131a20af0'

```

Code;
```
- (instancetype) initWithPathString:(NSString *)d
{
    if (self = [super init]) {
        NSRegularExpression* decimalRegularExpression = [[NSRegularExpression alloc] initWithPattern:@"(\\.\\d+)(?=\\-?\\.)" options:0 error:nil];
        _originD = d;

         // ERROR ON THE LINE BELOW //
        _d = [decimalRegularExpression stringByReplacingMatchesInString:d options:0 range:NSMakeRange(0, [d length]) withTemplate:@"$1\,"];
         // ERROR ON THE LINE ABOVE // 


        _pathRegularExpression = [[NSRegularExpression alloc] initWithPattern:@"[a-df-z]|[\\-+]?(?:[\\d.]e[\\-+]?|[^\\s\\-+,a-z])+" options:NSRegularExpressionCaseInsensitive error:nil];
    }
    return self;
}

```

**Comment by amsul** [comment]
I'm having the exact same issue, but with https://github.com/bgryszko/react-native-circular-progress

Not sure if it's a ReactNativeART related issue, but it definitely only started to appear after upgrading to RN 0.40

**Comment by airman00** [comment]
Update: it appears the issue is that an NSArray is being passed to initWithPathString

Variable d looks like this:
```
Array = (
    0,
    25,
    "0.5",
    3,
    "37.05136958558768",
    "0.5",
    "47.31311479045736",
    "9.264358378626531",
    "49.19836434458087",
    "21.16735560651435",
    3,
    "51.08361389870439",
    "33.07035283440216",
    "44.0324499368406",
    "44.5768066417913",
    "32.57091636218621",
    "48.30088464923126",
    3,
    "21.10938278753182",
    "52.02496265667122",
    "8.641547458091914",
    "46.86061616978279",
    "3.170340157384985",
    "36.1227672436189",
    3,
    "-2.300867143321941",
    "25.384918317455",
    "0.8494985186006012",
    "12.26270095014829",
    "10.5992613188344",
    "5.17908363781379"
)
```

instead of one long path string similar to this format: 

> M 0 100 C 3.75 95.125 8.75 90.11 12.5 86.45 S 21.25 78.495 25 75.6 S 33.75 69.37 37.5 67.15 S 46.25 62.435 50 60.8 S 58.75 57.39 62.5 56.25 S 71.25 53.935 75 53.2 S 83.75 51.77 87.5 51.35 S 96.25 50.595 100 50.4 

Try it for yourself by swapping in this code for initWithPathString:
```
- (instancetype) initWithPathString:(NSString *)d
{
    if (self = [super init]) {
        
        if ([d isKindOfClass:[NSArray class]]){
            NSArray* dArr = (NSArray*) d;
            NSLog(@"It's an Array = %@",dArr);
            
            
        }
        NSRegularExpression* decimalRegularExpression = [[NSRegularExpression alloc] initWithPattern:@"(\\.\\d+)(?=\\-?\\.)" options:0 error:nil];
        _originD = d;
        _d = [decimalRegularExpression stringByReplacingMatchesInString:d options:0 range:NSMakeRange(0, [d length]) withTemplate:@"$1\,"];
        _pathRegularExpression = [[NSRegularExpression alloc] initWithPattern:@"[a-df-z]|[\\-+]?(?:[\\d.]e[\\-+]?|[^\\s\\-+,a-z])+" options:NSRegularExpressionCaseInsensitive error:nil];
    }
    return self;
}
```

I can't just convert NSArray to a NSString because there doesn't seem to be any commands (e.g. M, S, C)... only numbers.


Anyone have any ideas to try?

**Comment by amsul** [comment]
Well, there seems to be a mapping of the path "movements": https://github.com/facebook/react-native/blob/11b515b1b0c25eec3e02f840373fc94c2f6b34b2/Libraries/ART/ARTSerializablePath.js#L18-L22

Just not sure how that is meant to be converted (without manually doing it)

**Comment by dr2391** [comment]
Just upgraded to 0.40 and I'm experiencing this as well

**Comment by oblador** [comment]
This is really strange as nothing seems to have changed in quite a while in this area. I just tried it on a fresh project and it works well for me, can anybody posts minimal steps to reproduce?

**Comment by amsul** [comment]
I can confirm that it's working with a new project. However, as soon as I add a component that uses react-native-svg, I start getting this error again.

So basically, any view that renders both react-native-progress as well as react-native-svg will fail. Using them in isolation seems to work though.

**Comment by oblador** [comment]
Sounds like a conflict between rnsvg and ART then? I'm guessing you updated rnsvg as everything else is more or less unchanged?

**Comment by dr2391** [comment]
Any update on this issue? I'm not sure how I can help

**Comment by Davidmeteor** [comment]
Blocked by the same issue with [](https://github.com/capitalone/react-native-pathjs-charts
)
[__NSArrayM length]: unrecognized selector sent to instance 0x600000657be0
2017-02-19 20:37:00.389 TWFinTech[2883:44690] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM length]: unrecognized selector sent to instance 0x600000657be0'

Any update on this one? Thanks!

**Comment by Davidmeteor** [comment]
Blocked by the same issue

[__NSArrayM length]: unrecognized selector sent to instance 0x600000657be0
2017-02-19 20:37:00.389 TWFinTech[2883:44690] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM length]: unrecognized selector sent to instance 0x600000657be0'

Any update on this one? Thanks!

**Comment by nuravdhiman** [comment]
Blocked by the same issue. Can anyone please help on this.

**Comment by irfanayazfm** [comment]
Same here. Blocked!

**Comment by oblador** [comment]
This bug was caused by react-native-svg and should be fixed in the latest version of that library.

**Comment by azhararmar** [comment]
I am facing this issue. I had react-native-svg installed, I removed it, it still shows me the same error.

<img width="300" alt="Screenshot 2019-03-09 at 11 53 50 PM" src="https://user-images.githubusercontent.com/10097624/54075533-a161a680-42c6-11e9-81fb-4e206c5d3c18.png">

**Comment by azhararmar** [comment]
It turns out the issue is when I use width={'100%'}, I had missed the documentation, when I looked back again and set the width value to null, it is working again.
